parameters: {}
environment: {}
packages:
    - name: chart
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: image
          binary: false
          main: ""
          runtime: nodejs:default
          web: true
          webSecure: false
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
